export const VIEW_USER_NAME = 'VIEW_USER_NAME';
export const SET_NEW_USER = 'SET_NEW_USER';

export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';

export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_FETCHED = "USER_FETCHED";

export const PROFILE_FETCHED = "PROFILE_FETCHED";
