export const VIEW_USER_NAME = 'VIEW_USER_NAME';
export const SET_NEW_USER = 'SET_NEW_USER';

export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';

export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_FETCHED = "USER_FETCHED";
export const USER_CHANGE_AVATAR = "USER_CHANGED_AVATAR";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE"

export const PROFILE_FETCHED = "PROFILE_FETCHED";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const CREATE_FOSSIL = "CREATE_FOSSIL";
export const FOSSIL_FETCHED = "FOSSIL_FETCHED";
export const ALL_FOSSILS_FETCHED = "ALL_FOSSILS_FETCHED";
export const USER_FOSSILS_FETCHED = "USER_FOSSILS_FETCHED";
export const ADD_DINO_CLAPS = "ADD_DINO_CLAPS";

export const SET_TO_LOADING = "SET_TO_LOADING";
